### ISSUE TITLE
Flagging taking longer for a single SPW

### ISSUE THREAD

**Issue by mb010** [idia-astro/pipelines#54]
When calibrating pointings using the default 12hrs time limit, I have found that some SPWs have failed due to time outs specifically on the `flagging_round_2` job (to the best of my knowledge). This seems to be repeatable when calibrating the same pointing (1462~1534MHz for `1587911796_sdp_l0.4k.ms`). This can be avoided by doubling (or more) the upper limit for the slurm job run times, but this is considered bad practice, so I'm hoping there is a software solution.

**Comment by mb010** [comment]
## Data on Processing
I present the data from our Ganglia monitoring system on a SPW which operated successfully (`880~952MHz`) and one which did not even after raising the run time to 24 hrs (`1462~1534MHz`).

# 880~952MHz
```
SPW #1: /share/nas2/MIGHTEE/calibration/cosmos/6.4_test/880~952MHz
          JobID         JobName  Partition    Elapsed NNodes NTasks NCPUS  MaxDiskRead MaxDiskWrite             NodeList   TotalCPU    CPUTime     MaxRSS      State ExitCode 
--------------- --------------- ---------- ---------- ------ ------ ----- ------------ ------------ -------------------- ---------- ---------- ---------- ---------- -------- 
28314           flag_round_2       CLUSTER   00:22:47      2           16                            compute-0-[109-110]   01:28:09   06:04:32             COMPLETED      0:0 
28314.batch     batch                        00:22:47      1      1     8       63.06G        5.78G        compute-0-109  34:50.418   03:02:16     40.79G  COMPLETED      0:0 
28314.0         orted                        00:22:46      1      1     1       70.01G        1.12G        compute-0-110  53:19.341   00:22:46     49.91G  COMPLETED      0:0 
28315           xy_yx_solve        CLUSTER   00:08:28      1            1                                  compute-0-110  04:21.893   00:08:28             COMPLETED      0:0 
28315.batch     batch                        00:08:28      1      1     1        0.16M        0.02M        compute-0-110  00:00.034   00:08:28      0.01G  COMPLETED      0:0 
28315.0         singularity                  00:08:28      1      1     1       27.76G        0.01G        compute-0-110  04:21.859   00:08:28      0.69G  COMPLETED      0:0 
28316           xy_yx_apply        CLUSTER   00:11:27      2           16                            compute-0-[105,110]  13:53.492   03:03:12             COMPLETED      0:0 
28316.batch     batch                        00:11:27      1      1     8       91.48G       38.27G        compute-0-105  07:43.828   01:31:36      2.44G  COMPLETED      0:0 
28316.0         orted                        00:11:27      1      1     1       69.41G       27.70G        compute-0-110  06:09.663   00:11:27      2.37G  COMPLETED      0:0 
28317           split              CLUSTER   00:10:23      2           16                            compute-0-[112,115]  13:44.807   02:46:08             COMPLETED      0:0 
28317.batch     batch                        00:10:23      1      1     8       39.22G       25.95G        compute-0-112  05:46.912   01:23:04      2.51G  COMPLETED      0:0 
28317.0         orted                        00:10:23      1      1     1       54.44G       36.15G        compute-0-115  07:57.894   00:10:23      2.74G  COMPLETED      0:0 
28318           quick_tclean       CLUSTER   00:20:04      2           32                            compute-0-[101,119]  53:46.529   10:42:08             COMPLETED      0:0 
28318.batch     batch                        00:20:04      1      1    16      103.15G       10.09G        compute-0-101  26:36.892   05:21:04      4.02G  COMPLETED      0:0 
28318.0         orted                        00:20:03      1      1     2      107.27G        6.64G        compute-0-119  27:09.637   00:40:06      4.13G  COMPLETED      0:0
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

The reports for the functioning SPW:

compute-0-109 (1/2 nodes used for completed flag_round_2)
![image](https://user-images.githubusercontent.com/51884241/147116485-5713b03e-efb1-4ef1-9071-ef88264d1bc3.png)
compute-0-110 (2/2 nodes used for completed flag_round_2)
![image](https://user-images.githubusercontent.com/51884241/147116114-1dbc08ba-2395-4db1-a637-977e439c43bf.png)


# 1462~1534MHz
```
SPW #8: /share/nas2/MIGHTEE/calibration/cosmos/6.4_test/1462~1534MHz
          JobID         JobName  Partition    Elapsed NNodes NTasks NCPUS  MaxDiskRead MaxDiskWrite             NodeList   TotalCPU    CPUTime     MaxRSS      State ExitCode 
--------------- --------------- ---------- ---------- ------ ------ ----- ------------ ------------ -------------------- ---------- ---------- ---------- ---------- -------- 
28390           flag_round_2       CLUSTER 1-00:00:14      2           16                            compute-0-[115-116]   07:37:36 16-00:03:44               TIMEOUT      0:0 
28390.batch     batch                      1-00:00:14      1      1     8        0.10G        0.09M        compute-0-115   07:37:36 8-00:01:52      1.09G  CANCELLED     0:15 
28390.0         orted                      1-00:01:14      1      1     1        0.10G        0.10M        compute-0-116  00:00.669 1-00:01:14      1.09G  CANCELLED      0:9 
28391           xy_yx_solve        CLUSTER   00:00:00      1            1                                  None assigned   00:00:00   00:00:00             CANCELLED      0:0 
28392           xy_yx_apply        CLUSTER   00:00:00      2           16                                  None assigned   00:00:00   00:00:00             CANCELLED      0:0 
28393           split              CLUSTER   00:00:00      2           16                                  None assigned   00:00:00   00:00:00             CANCELLED      0:0 
28394           quick_tclean       CLUSTER   00:00:00      2           32                                  None assigned   00:00:00   00:00:00             CANCELLED      0:0
```

The reports for the slow (and timed out) SPW:
**NOTE**: The spike in compute-0-116 is from selfcal partially running on said node after the timeout.

compute-0-115 (1/2 nodes used for completed flag_round_2)
![image](https://user-images.githubusercontent.com/51884241/147115645-6f5149b6-7f5d-4304-874a-8337b566a2ff.png)

compute-0-116 (2/2 nodes used for completed flag_round_2)
![image](https://user-images.githubusercontent.com/51884241/147116606-f5c8852a-fff8-4158-b9ef-d84ef83e8076.png)

**Comment by Jordatious** [comment]
Hi @mb010, thanks for submitting your issue. Having different run-times for the same step across different SPWs is very unusual, especially if they're equal in width (72 MHz in your two examples above). I see your successful SPW completed the 2nd round of flagging in ~23 minutes, so something is definitely going wrong with the other SPW taking > 12 hours, meaning increasing the wall-time won't address the issue.

Can you check the error logs and see what happened? Are you getting something like [this](https://idia-pipelines.github.io/docs/processMeerKAT/Diagnosing-Errors#server-timeout-errors)? This often shows up during flagging but it is a false positive error. If so, you could shorten the wall-time to a little longer than it actually takes (before encountering this error), and remove this job's dependency by editing the `submit_pipeline.sh` script inside that SPW, before running `./submit_pipeline.sh` from the top directory, which will enable the pipeline to keep running without terminating after hitting this error.

More generally, since each SPW should have very similar requirements for a given job, we would like to move toward a model where dynamic SLURM parameters are used, but with the same values for each job within each SPW. For example, you could use the following kind of syntax to allocate low memory and wall-time in general, but increase it for some jobs:

```
[slurm]                           # See processMeerKAT.py -h for documentation
nodes = 1
ntasks_per_node = 8
mem = 50                          # Use this many GB of memory (per node)
time = '01:00:00'
  .
  .
  .

precal_scripts =  [{'calc_refant.py',False}, {'partition.py',True}]

postcal_scripts = [{'concat.py',False,mem=10}, 
		  {'plotcal_spw.py',False,mem=10}, 
		  {'selfcal_part1.py',True,ntasks_per_node=16,time=05:00:00}, 
		  {'selfcal_part2.py',False,time=02:00:00}, 
		  {'science_image.py',True,ntasks_per_node=16,time=05:00:00}]

scripts = 	 [{'validate_input.py',False,mem=10},
		  {'flag_round_1.py',True,mem=100},
		  {'calc_refant.py',False},
		  {'setjy.py',True},
		  {'xx_yy_solve.py',False},
  		  {'xx_yy_apply.py',True},
		  {'flag_round_2.py',True,mem=100},
		  {'xx_yy_solve.py',False},
		  {'xx_yy_apply.py',True},
		  {'split.py',True},
		  {'quick_tclean.py',True},
		  {'plot_solutions.py',False,mem=10}]
```

This would be a future feature in a future release if we implement it. For now, when using nspw>1, you can use the following syntax to edit pipeline scripts before they're submitted (e.g. if flagging should take 2 hours instead of 1 hour, as an extreme example).

```
sed -i "s/time=01:00:00/time=02:00:00/g" */flag_round_?.sbatch
```

The same is possible for any of the SLURM parameters before launching the pipeline.

**Comment by mb010** [comment]
Hi @Jordatious, I just checked and it seems like there isnt a `*.casa` file produced from the `flag_round_2` run on the failed spw. The .err file reads:
```
[mbowles@galahad logs]$ cat flag_round_2-28390.err 
Warning: program compiled against libxml 209 using older 207
Warning: program compiled against libxml 209 using older 207
Warning: program compiled against libxml 209 using older 207
Warning: program compiled against libxml 209 using older 207
Warning: program compiled against libxml 209 using older 207
Warning: program compiled against libxml 209 using older 207
Warning: program compiled against libxml 209 using older 207
Warning: program compiled against libxml 209 using older 207
Warning: program compiled against libxml 209 using older 207
Warning: program compiled against libxml 209 using older 207
Warning: program compiled against libxml 209 using older 207
Warning: program compiled against libxml 209 using older 207
Warning: program compiled against libxml 209 using older 207
Warning: program compiled against libxml 209 using older 207
Warning: program compiled against libxml 209 using older 207
Warning: program compiled against libxml 209 using older 207
slurmstepd: error: *** JOB 28390 ON compute-0-115 CANCELLED AT 2021-12-22T14:33:38 DUE TO TIME LIMIT ***
mpirun: Forwarding signal 18 to job
```
Although this looks bad, everything I found makes this seem like a largely insignificant warning. Importantly, these warnings for each mpi instance are also listed in the logs of the spws which did not fail. There is a slew of 'severe' casa errors in the logs of the other spws, and I havent been able to figure out which may be meaningful and which arent. These seem to align well with the [link](https://idia-pipelines.github.io/docs/processMeerKAT/Diagnosing-Errors/#server-timeout-errors) that you shared (here an excerpt):

```
2021-12-21 14:08:07	SEVERE	MPICommandClient::command_response_handler_service::MPICommandClient::command_response_handler_service::casa	Command request with id 15 failed in server n# 1 with traceback Traceback (most recent call last):
2021-12-21 14:08:07	SEVERE	MPICommandClient::command_response_handler_service::MPICommandClient::command_response_handler_service::casa+	  File "/anaconda3/lib/python3.6/site-packages/casampi/private/MPICommandServer.py", line 208, in __command_request_handler_service
2021-12-21 14:08:07	SEVERE	MPICommandClient::command_response_handler_service::MPICommandClient::command_response_handler_service::casa+	    command_response['ret'] = eval(eval_str)
2021-12-21 14:08:07	SEVERE	MPICommandClient::command_response_handler_service::MPICommandClient::command_response_handler_service::casa+	  File "<string>", line 1, in <module>
2021-12-21 14:08:07	SEVERE	MPICommandClient::command_response_handler_service::MPICommandClient::command_response_handler_service::casa+	  File "/anaconda3/lib/python3.6/site-packages/casatasks/flagdata.py", line 1135, in __call__
2021-12-21 14:08:07	SEVERE	MPICommandClient::command_response_handler_service::MPICommandClient::command_response_handler_service::casa+	    task_result = _flagdata_t( _pc.document['vis'], _pc.document['mode'], _pc.document['autocorr'], _pc.document['inpfile'], _pc.document['reason'], _pc.document['tbuff'], _pc.document['spw'], _pc.document['field'], _pc.document['antenna'], _pc.document['uvrange'], _pc.document['timerange'], _pc.document['correlation'], _pc.document['scan'], _pc.document['intent'], _pc.document['array'], _pc.document['observation'], _pc.document['feed'], _pc.document['clipminmax'], _pc.document['datacolumn'], _pc.document['clipoutside'], _pc.document['channelavg'], _pc.document['chanbin'], _pc.document['timeavg'], _pc.document['timebin'], _pc.document['clipzeros'], _pc.document['quackinterval'], _pc.document['quackmode'], _pc.document['quackincrement'], _pc.document['tolerance'], _pc.document['addantenna'], _pc.document['lowerlimit'], _pc.document['upperlimit'], _pc.document['ntime'], _pc.document['combinescans'], _pc.document['timecutoff'], _pc.document['freqcutoff'], _pc.document['timefit'], _pc.document['freqfit'], _pc.document['maxnpieces'], _pc.document['flagdimension'], _pc.document['usewindowstats'], _pc.document['halfwin'], _pc.document['extendflags'], _pc.document['winsize'], _pc.document['timedev'], _pc.document['freqdev'], _pc.document['timedevscale'], _pc.document['freqdevscale'], _pc.document['spectralmax'], _pc.document['spectralmin'], _pc.document['antint_ref_antenna'], _pc.document['minchanfrac'], _pc.document['verbose'], _pc.document['extendpols'], _pc.document['growtime'], _pc.document['growfreq'], _pc.document['growaround'], _pc.document['flagneartime'], _pc.document['flagnearfreq'], _pc.document['minrel'], _pc.document['maxrel'], _pc.document['minabs'], _pc.document['maxabs'], _pc.document['spwchan'], _pc.document['spwcorr'], _pc.document['basecnt'], _pc.document['fieldcnt'], _pc.document['name'], _pc.document['action'], _pc.document['display'], _pc.document['flagbackup'], _pc.document['savepars'], _pc.document['cmdreason'], _pc.document['outfile'], _pc.document['overwrite'], _pc.document['writeflags'] )
2021-12-21 14:08:07	SEVERE	MPICommandClient::command_response_handler_service::MPICommandClient::command_response_handler_service::casa+	  File "/anaconda3/lib/python3.6/site-packages/casatasks/private/task_flagdata.py", line 643, in flagdata
2021-12-21 14:08:07	SEVERE	MPICommandClient::command_response_handler_service::MPICommandClient::command_response_handler_service::casa+	    intent=intent, observation=str(observation))
2021-12-21 14:08:07	SEVERE	MPICommandClient::command_response_handler_service::MPICommandClient::command_response_handler_service::casa+	  File "/anaconda3/lib/python3.6/site-packages/casatools/agentflagger.py", line 44, in selectdata
2021-12-21 14:08:07	SEVERE	MPICommandClient::command_response_handler_service::MPICommandClient::command_response_handler_service::casa+	    return self._swigobj.selectdata(_dict_ec(config), _str_ec(field), _str_ec(spw), _str_ec(array), _str_ec(feed), _str_ec(scan), _str_ec(antenna), _str_ec(uvrange), _str_ec(timerange), _str_ec(correlation), _str_ec(intent), _str_ec(observation))
2021-12-21 14:08:07	SEVERE	MPICommandClient::command_response_handler_service::MPICommandClient::command_response_handler_service::casa+	  File "/anaconda3/lib/python3.6/site-packages/casatools/__casac__/agentflagger.py", line 197, in selectdata
2021-12-21 14:08:07	SEVERE	MPICommandClient::command_response_handler_service::MPICommandClient::command_response_handler_service::casa+	    return _agentflagger.agentflagger_selectdata(self, *args, **kwargs)
2021-12-21 14:08:07	SEVERE	MPICommandClient::command_response_handler_service::MPICommandClient::command_response_handler_service::casa+	RuntimeError: MSSelectionNullSelection : The selected table has zero rows.
```

**Comment by Jordatious** [comment]
Hi @mb010, that's strange. The lack of the `*.casa` log suggests CASA did not run. Do you know if it did? It almost seems like SLURM is hanging the entire time waiting for CASA to run. If that's the case, I'd probably have to get hold of the data to see if I can reproduce the error and determine what's happening. But I think it's unlikely that this is a pipeline error.

This error you pasted at the end corresponds to [this error](https://idia-pipelines.github.io/docs/processMeerKAT/Diagnosing-Errors/#empty-rows-in-sub-mss), which is another false positive error:

```
RuntimeError: MSSelectionNullSelection : The selected table has zero rows.
```

**Comment by Jordatious** [comment]
Hi @mb010, is this issue resolved? May I close the ticket now?
