### ISSUE TITLE
Module 'processMeerKAT' has no attribute 'get_spw_bounds'

### ISSUE THREAD

**Issue by manuparra** [idia-astro/pipelines#60]
Working with the pipeline I see the next error related to function `get_spw_bounds()`:

```
cat logs/concat-1375.err
/var/spool/slurmd/job01375/slurm_script: line 14: module: command not found
2024-01-24 14:33:53,001 ERROR: Exception found in the pipeline of type <class 'AttributeError'>: module 'processMeerKAT' has no attribute 'get_spw_bounds'
2024-01-24 14:33:53,005 ERROR: Traceback (most recent call last):
  File "/mnt/slurm-jobs/meerkat-pipeline-custom-hpc/processMeerKAT/bookkeeping.py", line 285, in run_script
    func(args,taskvals)
  File "/mnt/slurm-jobs/meerkat-pipeline-custom-hpc/processMeerKAT/aux_scripts/concat.py", line 166, in main
    dirs = config_parser.parse_spw(args['config'])[3]
  File "/mnt/slurm-jobs/meerkat-pipeline-custom-hpc/processMeerKAT/config_parser.py", line 106, in parse_spw
    low[i],high[i],unit[i],func = processMeerKAT.get_spw_bounds(SPW)
AttributeError: module 'processMeerKAT' has no attribute 'get_spw_bounds'
```
Any ideas?

**Comment by manuparra** [comment]
I think that it is an issue with the package. The package have the same name for the main processMeerKAT.py. I'm thinking, a pip package or to move the functions inside processMeerKAT.py to another module to be imported correctly from the call of the functions.

**Comment by manuparra** [comment]
Solving... I will paste the solution :)

**Comment by manuparra** [comment]
Wrong parameterisation and path. Solved.
